name: Deploy Django App to AWS EC2

on:
  push:
    branches:
      - main  # Run deployment on push to main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 16.171.93.97 >> ~/.ssh/known_hosts

    - name: Deploy to EC2 and restart app
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@16.171.93.97 << 'EOF'
          cd /home/ubuntu/movie_ticket_booking_M1
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput
          sudo systemctl restart django_app
        EOF
